// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/add.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalClient is the client API for Cal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalClient interface {
	Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type calClient struct {
	cc grpc.ClientConnInterface
}

func NewCalClient(cc grpc.ClientConnInterface) CalClient {
	return &calClient{cc}
}

func (c *calClient) Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/proto.cal/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalServer is the server API for Cal service.
// All implementations must embed UnimplementedCalServer
// for forward compatibility
type CalServer interface {
	Do(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedCalServer()
}

// UnimplementedCalServer must be embedded to have forward compatible implementations.
type UnimplementedCalServer struct {
}

func (UnimplementedCalServer) Do(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedCalServer) mustEmbedUnimplementedCalServer() {}

// UnsafeCalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalServer will
// result in compilation errors.
type UnsafeCalServer interface {
	mustEmbedUnimplementedCalServer()
}

func RegisterCalServer(s grpc.ServiceRegistrar, srv CalServer) {
	s.RegisterService(&Cal_ServiceDesc, srv)
}

func _Cal_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cal/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalServer).Do(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Cal_ServiceDesc is the grpc.ServiceDesc for Cal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.cal",
	HandlerType: (*CalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Cal_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/add.proto",
}
